#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TimePilot.Resource", IsApplication=true)]

namespace TimePilot
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int angrybirds = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cam360 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int camera = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int downloads = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dropbox = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int evernote = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int evernotealt = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int fruitninja = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int gtalk = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int handcent = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int maps = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int mydeleteButtonImage = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int recorder = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int red_arrow_100x100_72 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int settingsa = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int tasks = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int twitterblue = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int widgetlocker = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int youtube = 2130837522;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int delete = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int imageView_item = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int linearlayout_text = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int textview_bottom = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int textview_top = 2131034114;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
